# Netlify Configuration for JSG Logger DevTools
# Deploys the DevTools test application from the devtools/ subdirectory

[build]
  # Base directory for build commands (monorepo subdirectory)
  base = "devtools"
  
  # Build command - install deps and build standalone app
  command = "npm install && npm run build:netlify"
  
  # Publish directory relative to base
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# SPA redirect rule - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

